#!/bin/bash
PATH_TO_FIND="$1"
TEXT_TO_FIND="$2"
for i in $(find "$PATH_TO_FIND" -type f); do 
    if [ $(grep -o -e "$TEXT_TO_FIND" $i | wc -l | cut -d" " -f1) -gt 0 ]; 
    then 
        echo $i; 
    fi; 
done
